snap-core.cabal: add missing tests file to source tarball
Otherwise 'cabal test' failed as:
  test/TestSuite.hs:16:1: error:
    Failed to load interface for ‘Snap.Util.CORS.Tests’
    Use -v to see a list of the files searched for.

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>